/**
 * Built-in configurations from the W3C Sanitizer API spec.
 * @see https://wicg.github.io/sanitizer-api/#sanitization-defaults
 */

import type { CanonicalConfig, CanonicalName, CanonicalElementWithAttributes } from "./types.ts";
import { HTML_NAMESPACE, SVG_NAMESPACE, MATHML_NAMESPACE } from "./constants.ts";

function el(
  name: string,
  namespace: string,
  attributes: CanonicalName[] = [],
): CanonicalElementWithAttributes {
  return { name, namespace, attributes, removeAttributes: [] };
}

function attr(name: string): CanonicalName {
  return { name, namespace: null };
}

/** The built-in safe default configuration (allowlist-based). */
export const BUILT_IN_SAFE_DEFAULT_CONFIG: CanonicalConfig = {
  elements: [
    // MathML elements
    el("math", MATHML_NAMESPACE),
    el("merror", MATHML_NAMESPACE),
    el("mfrac", MATHML_NAMESPACE),
    el("mi", MATHML_NAMESPACE),
    el("mmultiscripts", MATHML_NAMESPACE),
    el("mn", MATHML_NAMESPACE),
    el("mo", MATHML_NAMESPACE, [
      attr("fence"), attr("form"), attr("largeop"), attr("lspace"),
      attr("maxsize"), attr("minsize"), attr("movablelimits"),
      attr("rspace"), attr("separator"), attr("stretchy"), attr("symmetric"),
    ]),
    el("mover", MATHML_NAMESPACE, [attr("accent")]),
    el("mpadded", MATHML_NAMESPACE, [
      attr("depth"), attr("height"), attr("lspace"), attr("voffset"), attr("width"),
    ]),
    el("mphantom", MATHML_NAMESPACE),
    el("mprescripts", MATHML_NAMESPACE),
    el("mroot", MATHML_NAMESPACE),
    el("mrow", MATHML_NAMESPACE),
    el("ms", MATHML_NAMESPACE),
    el("mspace", MATHML_NAMESPACE, [attr("depth"), attr("height"), attr("width")]),
    el("msqrt", MATHML_NAMESPACE),
    el("mstyle", MATHML_NAMESPACE),
    el("msub", MATHML_NAMESPACE),
    el("msubsup", MATHML_NAMESPACE),
    el("msup", MATHML_NAMESPACE),
    el("mtable", MATHML_NAMESPACE),
    el("mtd", MATHML_NAMESPACE, [attr("columnspan"), attr("rowspan")]),
    el("mtext", MATHML_NAMESPACE),
    el("mtr", MATHML_NAMESPACE),
    el("munder", MATHML_NAMESPACE, [attr("accentunder")]),
    el("munderover", MATHML_NAMESPACE, [attr("accent"), attr("accentunder")]),
    el("semantics", MATHML_NAMESPACE),

    // HTML elements
    el("a", HTML_NAMESPACE, [attr("href"), attr("hreflang"), attr("type")]),
    el("abbr", HTML_NAMESPACE),
    el("address", HTML_NAMESPACE),
    el("article", HTML_NAMESPACE),
    el("aside", HTML_NAMESPACE),
    el("b", HTML_NAMESPACE),
    el("bdi", HTML_NAMESPACE),
    el("bdo", HTML_NAMESPACE),
    el("blockquote", HTML_NAMESPACE, [attr("cite")]),
    el("body", HTML_NAMESPACE),
    el("br", HTML_NAMESPACE),
    el("caption", HTML_NAMESPACE),
    el("cite", HTML_NAMESPACE),
    el("code", HTML_NAMESPACE),
    el("col", HTML_NAMESPACE, [attr("span")]),
    el("colgroup", HTML_NAMESPACE, [attr("span")]),
    el("data", HTML_NAMESPACE, [attr("value")]),
    el("dd", HTML_NAMESPACE),
    el("del", HTML_NAMESPACE, [attr("cite"), attr("datetime")]),
    el("dfn", HTML_NAMESPACE),
    el("div", HTML_NAMESPACE),
    el("dl", HTML_NAMESPACE),
    el("dt", HTML_NAMESPACE),
    el("em", HTML_NAMESPACE),
    el("figcaption", HTML_NAMESPACE),
    el("figure", HTML_NAMESPACE),
    el("footer", HTML_NAMESPACE),
    el("h1", HTML_NAMESPACE),
    el("h2", HTML_NAMESPACE),
    el("h3", HTML_NAMESPACE),
    el("h4", HTML_NAMESPACE),
    el("h5", HTML_NAMESPACE),
    el("h6", HTML_NAMESPACE),
    el("head", HTML_NAMESPACE),
    el("header", HTML_NAMESPACE),
    el("hgroup", HTML_NAMESPACE),
    el("hr", HTML_NAMESPACE),
    el("html", HTML_NAMESPACE),
    el("i", HTML_NAMESPACE),
    el("ins", HTML_NAMESPACE, [attr("cite"), attr("datetime")]),
    el("kbd", HTML_NAMESPACE),
    el("li", HTML_NAMESPACE, [attr("value")]),
    el("main", HTML_NAMESPACE),
    el("mark", HTML_NAMESPACE),
    el("menu", HTML_NAMESPACE),
    el("nav", HTML_NAMESPACE),
    el("ol", HTML_NAMESPACE, [attr("reversed"), attr("start"), attr("type")]),
    el("p", HTML_NAMESPACE),
    el("pre", HTML_NAMESPACE),
    el("q", HTML_NAMESPACE),
    el("rp", HTML_NAMESPACE),
    el("rt", HTML_NAMESPACE),
    el("ruby", HTML_NAMESPACE),
    el("s", HTML_NAMESPACE),
    el("samp", HTML_NAMESPACE),
    el("search", HTML_NAMESPACE),
    el("section", HTML_NAMESPACE),
    el("small", HTML_NAMESPACE),
    el("span", HTML_NAMESPACE),
    el("strong", HTML_NAMESPACE),
    el("sub", HTML_NAMESPACE),
    el("sup", HTML_NAMESPACE),
    el("table", HTML_NAMESPACE),
    el("tbody", HTML_NAMESPACE),
    el("td", HTML_NAMESPACE, [attr("colspan"), attr("headers"), attr("rowspan")]),
    el("tfoot", HTML_NAMESPACE),
    el("th", HTML_NAMESPACE, [
      attr("abbr"), attr("colspan"), attr("headers"), attr("rowspan"), attr("scope"),
    ]),
    el("thead", HTML_NAMESPACE),
    el("time", HTML_NAMESPACE, [attr("datetime")]),
    el("title", HTML_NAMESPACE),
    el("tr", HTML_NAMESPACE),
    el("u", HTML_NAMESPACE),
    el("ul", HTML_NAMESPACE),
    el("var", HTML_NAMESPACE),
    el("wbr", HTML_NAMESPACE),

    // SVG elements
    el("a", SVG_NAMESPACE, [attr("href"), attr("hreflang"), attr("type")]),
    el("circle", SVG_NAMESPACE, [attr("cx"), attr("cy"), attr("pathLength"), attr("r")]),
    el("defs", SVG_NAMESPACE),
    el("desc", SVG_NAMESPACE),
    el("ellipse", SVG_NAMESPACE, [
      attr("cx"), attr("cy"), attr("pathLength"), attr("rx"), attr("ry"),
    ]),
    el("foreignObject", SVG_NAMESPACE, [
      attr("height"), attr("width"), attr("x"), attr("y"),
    ]),
    el("g", SVG_NAMESPACE),
    el("line", SVG_NAMESPACE, [
      attr("pathLength"), attr("x1"), attr("x2"), attr("y1"), attr("y2"),
    ]),
    el("marker", SVG_NAMESPACE, [
      attr("markerHeight"), attr("markerUnits"), attr("markerWidth"),
      attr("orient"), attr("preserveAspectRatio"),
      attr("refX"), attr("refY"), attr("viewBox"),
    ]),
    el("metadata", SVG_NAMESPACE),
    el("path", SVG_NAMESPACE, [attr("d"), attr("pathLength")]),
    el("polygon", SVG_NAMESPACE, [attr("pathLength"), attr("points")]),
    el("polyline", SVG_NAMESPACE, [attr("pathLength"), attr("points")]),
    el("rect", SVG_NAMESPACE, [
      attr("height"), attr("pathLength"), attr("rx"), attr("ry"),
      attr("width"), attr("x"), attr("y"),
    ]),
    el("svg", SVG_NAMESPACE, [
      attr("height"), attr("preserveAspectRatio"), attr("viewBox"),
      attr("width"), attr("x"), attr("y"),
    ]),
    el("text", SVG_NAMESPACE, [
      attr("dx"), attr("dy"), attr("lengthAdjust"),
      attr("rotate"), attr("textLength"), attr("x"), attr("y"),
    ]),
    el("textPath", SVG_NAMESPACE, [
      attr("lengthAdjust"), attr("method"), attr("path"),
      attr("side"), attr("spacing"), attr("startOffset"), attr("textLength"),
    ]),
    el("title", SVG_NAMESPACE),
    el("tspan", SVG_NAMESPACE, [
      attr("dx"), attr("dy"), attr("lengthAdjust"),
      attr("rotate"), attr("textLength"), attr("x"), attr("y"),
    ]),
  ],
  attributes: [
    attr("alignment-baseline"),
    attr("baseline-shift"),
    attr("clip-path"),
    attr("clip-rule"),
    attr("color"),
    attr("color-interpolation"),
    attr("cursor"),
    attr("dir"),
    attr("direction"),
    attr("display"),
    attr("displaystyle"),
    attr("dominant-baseline"),
    attr("fill"),
    attr("fill-opacity"),
    attr("fill-rule"),
    attr("font-family"),
    attr("font-size"),
    attr("font-size-adjust"),
    attr("font-stretch"),
    attr("font-style"),
    attr("font-variant"),
    attr("font-weight"),
    attr("lang"),
    attr("letter-spacing"),
    attr("marker-end"),
    attr("marker-mid"),
    attr("marker-start"),
    attr("mathbackground"),
    attr("mathcolor"),
    attr("mathsize"),
    attr("opacity"),
    attr("paint-order"),
    attr("pointer-events"),
    attr("scriptlevel"),
    attr("shape-rendering"),
    attr("stop-color"),
    attr("stop-opacity"),
    attr("stroke"),
    attr("stroke-dasharray"),
    attr("stroke-dashoffset"),
    attr("stroke-linecap"),
    attr("stroke-linejoin"),
    attr("stroke-miterlimit"),
    attr("stroke-opacity"),
    attr("stroke-width"),
    attr("text-anchor"),
    attr("text-decoration"),
    attr("text-overflow"),
    attr("text-rendering"),
    attr("title"),
    attr("transform"),
    attr("transform-origin"),
    attr("unicode-bidi"),
    attr("vector-effect"),
    attr("visibility"),
    attr("white-space"),
    attr("word-spacing"),
    attr("writing-mode"),
  ],
  comments: false,
  dataAttributes: false,
};

/** The built-in safe baseline configuration (blocks only script content). */
export const BUILT_IN_SAFE_BASELINE_CONFIG: CanonicalConfig = {
  removeElements: [
    { name: "embed", namespace: HTML_NAMESPACE },
    { name: "frame", namespace: HTML_NAMESPACE },
    { name: "iframe", namespace: HTML_NAMESPACE },
    { name: "object", namespace: HTML_NAMESPACE },
    { name: "script", namespace: HTML_NAMESPACE },
    { name: "script", namespace: SVG_NAMESPACE },
    { name: "use", namespace: SVG_NAMESPACE },
  ],
  removeAttributes: [],
  comments: false,
};
